-- @description Reflex
-- @version 20.667
-- @author S.Hansen / Tycho
-- @link GitHub repository https://github.com/tychomusic/reapack
-- @link Requirements https://github.com/tychomusic/reapack#reflex
-- @changelog
--   Hide Remote by default, draw Reflex arrows font-independently on Windows, and update embedded Navigator mirror phase.
-- @metapackage
-- @provides
--   [main] Reflex.lua
--   [main] Navigator.lua
--   [main] Reflex_IOManager.lua
--   [main] Reflex_WindowToggle.lua
--   [main] Reflex_HistoryBack.lua
--   [main] Reflex_HistoryForward.lua
--   [nomain] Reflex_Theme_Default.lua
--   [nomain] core/*.lua
--   [nomain] icons/*.png
