-- @description Reflex
-- @version 20.677
-- @author S.Hansen / Tycho
-- @link GitHub repository https://github.com/tychomusic/reapack
-- @link Requirements https://github.com/tychomusic/reapack#reflex
-- @changelog
--   Refine FX unavailable state, MIDI input meters, and volume fader drag behavior.
-- @metapackage
-- @provides
--   [main] Reflex.lua
--   [main] Navigator.lua
--   [main] Reflex_IOManager.lua
--   [main] Reflex_WindowToggle.lua
--   [main] Reflex_AddFX.lua
--   [main] Reflex_CloseAllFXWindows.lua
--   [main] Reflex_FocusSearch.lua
--   [main] Reflex_OpenFXBrowser.lua
--   [main] Reflex_FXWindowNext.lua
--   [main] Reflex_FXWindowPrevious.lua
--   [main] Reflex_FXWindowStackNext.lua
--   [main] Reflex_FXWindowStackPrevious.lua
--   [main] Reflex_HistoryBack.lua
--   [main] Reflex_HistoryForward.lua
--   [main] Reflex_TileFXWindows.lua
--   [main] Reflex_Navigator_ArmedViewToggle.lua
--   [main] Reflex_Navigator_ScrollToRecordArmed.lua
--   [main] Reflex_Navigator_ToggleExpand.lua
--   [nomain] Reflex_ActionBridge.lua
--   [nomain] Reflex_NavigatorActionBridge.lua
--   [nomain] core/*.lua
--   [nomain] icons/*.png
