-- @description Reflex
-- @version 20.672
-- @author S.Hansen / Tycho
-- @link GitHub repository https://github.com/tychomusic/reapack
-- @link Requirements https://github.com/tychomusic/reapack#reflex
-- @changelog
--   Add draggable Navigator/Inspector split, fix embedded Navigator arrow rendering, and restore normal non-ReaperTips dock gaps.
-- @metapackage
-- @provides
--   [main] Reflex.lua
--   [main] Navigator.lua
--   [main] Reflex_IOManager.lua
--   [main] Reflex_WindowToggle.lua
--   [main] Reflex_HistoryBack.lua
--   [main] Reflex_HistoryForward.lua
--   [main] Reflex_Navigator_ArmedViewToggle.lua
--   [main] Reflex_Navigator_ScrollToRecordArmed.lua
--   [nomain] Reflex_NavigatorActionBridge.lua
--   [nomain] core/*.lua
--   [nomain] icons/*.png
